// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCvrNOOu7G57M_xvkx0rE-OI-tXr1QDg',
    appId: '1:185489267441:web:5ed25200b1706c2be9e750',
    messagingSenderId: '185489267441',
    projectId: 'museum-guide0',
    authDomain: 'museum-guide0.firebaseapp.com',
    storageBucket: 'museum-guide0.appspot.com',
    measurementId: 'G-1KS1L591KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlahC75pF5hoEfycceqUPoBTayxPQ4Ec',
    appId: '1:185489267441:android:feec54376de8edf6e9e750',
    messagingSenderId: '185489267441',
    projectId: 'museum-guide0',
    storageBucket: 'museum-guide0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVvTO8ALz7CR7VjnUci_cD_OFxHzyaxE',
    appId: '1:185489267441:ios:b56ea110d679b108e9e750',
    messagingSenderId: '185489267441',
    projectId: 'museum-guide0',
    storageBucket: 'museum-guide0.appspot.com',
    iosBundleId: 'com.example.meuseumGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVvTO8ALz7CR7VjnUci_cD_OFxHzyaxE',
    appId: '1:185489267441:ios:20c92f02bb4c5460e9e750',
    messagingSenderId: '185489267441',
    projectId: 'museum-guide0',
    storageBucket: 'museum-guide0.appspot.com',
    iosBundleId: 'com.example.meuseumGuide.RunnerTests',
  );
}
